// Mapping from manufacturer ID to manufacturer brand name
const manufacturers = {
    0: "unknown manufacturer",
    1: "garmin",
    2: "garmin_fr405_antfs",
    3: "zephyr",
    4: "dayton",
    5: "idt",
    6: "srm",
    7: "quarq",
    8: "ibike",
    9: "saris",
    10: "spark_hk",
    11: "tanita",
    12: "echowell",
    13: "dynastream_oem",
    14: "nautilus",
    15: "dynastream",
    16: "timex",
    17: "metrigear",
    18: "xelic",
    19: "beurer",
    20: "cardiosport",
    21: "a_and_d",
    22: "hmm",
    23: "suunto",
    24: "thita_elektronik",
    25: "gpulse",
    26: "clean_mobile",
    27: "pedal_brain",
    28: "peaksware",
    29: "saxonar",
    30: "lemond_fitness",
    31: "dexcom",
    32: "wahoo_fitness",
    33: "octane_fitness",
    34: "archinoetics",
    35: "the_hurt_box",
    36: "citizen_systems",
    37: "magellan",
    38: "osynce",
    39: "holux",
    40: "concept2",
    41: "shimano",
    42: "one_giant_leap",
    43: "ace_sensor",
    44: "brim_brothers",
    45: "xplova",
    46: "perception_digital",
    47: "bf1systems",
    48: "pioneer",
    49: "spantec",
    50: "metalogics",
    51: "4",
    52: "seiko_epson",
    53: "seiko_epson_oem",
    54: "ifor_powell",
    55: "maxwell_guider",
    56: "star_trac",
    57: "breakaway",
    58: "alatech_technology_ltd",
    59: "mio_technology_europe",
    60: "rotor",
    61: "geonaute",
    62: "id_bike",
    63: "specialized",
    64: "wtek",
    65: "physical_enterprises",
    66: "north_pole_engineering",
    67: "bkool",
    68: "cateye",
    69: "stages_cycling",
    70: "sigmasport",
    71: "tomtom",
    72: "peripedal",
    73: "wattbike",
    76: "moxy",
    77: "ciclosport",
    78: "powerbahn",
    79: "acorn_projects_aps",
    80: "lifebeam",
    81: "bontrager",
    82: "wellgo",
    83: "scosche",
    84: "magura",
    85: "woodway",
    86: "elite",
    87: "nielsen_kellerman",
    88: "dk_city",
    89: "tacx",
    90: "direction_technology",
    91: "magtonic",
    92: "1",
    93: "inside_ride_technologies",
    94: "sound_of_motion",
    95: "stryd",
    96: "icg",
    97: "MiPulse",
    98: "bsx_athletics",
    99: "look",
    100: "campagnolo_srl",
    101: "body_bike_smart",
    102: "praxisworks",
    103: "limits_technology",
    104: "topaction_technology",
    105: "cosinuss",
    106: "fitcare",
    107: "magene",
    108: "giant_manufacturing_co",
    109: "tigrasport",
    110: "salutron",
    111: "technogym",
    112: "bryton_sensors",
    113: "latitude_limited",
    114: "soaring_technology",
    115: "igpsport",
    116: "thinkrider",
    117: "gopher_sport",
    118: "waterrower",
    119: "orangetheory",
    120: "inpeak",
    121: "kinetic",
    122: "johnson_health_tech",
    123: "polar_electro",
    124: "seesense",
    125: "nci_technology",
    126: "iqsquare",
    127: "leomo",
    128: "ifit_com",
    129: "coros_byte",
    130: "versa_design",
    131: "chileaf",
    132: "cycplus",
    133: "gravaa_byte",
    134: "sigeyi",
    135: "coospo",
    255: "development",
    257: "healthandlife",
    258: "lezyne",
    259: "scribe_labs",
    260: "zwift",
    261: "watteam",
    262: "recon",
    263: "favero_electronics",
    264: "dynovelo",
    265: "strava",
    266: "precor",
    267: "bryton",
    268: "sram",
    269: "navman",
    270: "cobi",
    271: "spivi",
    272: "mio_magellan",
    273: "evesports",
    274: "sensitivus_gauge",
    275: "podoon",
    276: "life_time_fitness",
    277: "falco_e_motors",
    278: "minoura",
    279: "cycliq",
    280: "luxottica",
    281: "trainer_road",
    282: "the_sufferfest",
    283: "fullspeedahead",
    284: "virtualtraining",
    285: "feedbacksports",
    286: "omata",
    287: "vdo",
    288: "magneticdays",
    289: "hammerhead",
    290: "kinetic_by_kurt",
    291: "shapelog",
    292: "dabuziduo",
    293: "jetblack",
    294: "coros",
    295: "virtugo",
    296: "velosense",
    297: "cycligentinc",
    298: "trailforks",
    299: "mahle_ebikemotion",
    300: "nurvv",
    301: "microprogram",
    302: "zone5cloud",
    303: "greenteg",
    304: "yamaha_motors",
    305: "whoop",
    306: "gravaa",
    307: "onelap",
    308: "monark_exercise",
    309: "form",
    310: "decathlon",
    311: "syncros",
    5759: "actigraphcorp",
}

// Mapping from device ID to rider name
const riders = {
    672585: "Kenny De Ketele",
    394446: "Jolien D'hoore",
    21147: "Tuur Dens",
    30104: "Lotte Kopecky",
    40849: "Robbe Ghys",
    40923: "Jolien D'hoore",
    51777: "Tuur Dens",
    5995: "Brent Van Mulders",
    306: "Shari Bossuyt",
    22301: "Lotte Kopecky",
    40844: "Kenny De Ketele",
    47101: "Shari Bossuyt"
}

// Mapping from device ID to device type
const devices = {
    672585: "HRM - Garmin",
    394446: "HRM - Garmin",
    21147: "HRM - Wahoo",
    30104: "Power - SRM",
    40849: "Power - SRM",
    40923: "Power - SRM",
    51777: "Power - Stages",
    5995: "HRM - Garmin",
    306: "HRM - Garmin",
    22301: "HRM - SRM",
    40844: "Power - SRM",
    47101: "Power - 4iii"
}

// Data types to display on the dashboard
data_types = new Set(["SMO2", "Saturation", "Previous Saturation", "heartrate", "power", "cadence", "speed",
                        "run_cadence", "ground_contact_time", "vertical_ratio", "vertical_oscillation",
                        "stride_length", "tire_pressure_mbar", "sensor_location", "core_temperature_c",
                        "skin_temperature_c"]);
data_type_units = {
    "SMO2": "g/dl",
    "Saturation": "%",
    "Previous Saturation": "%",
    "cadence": "RPM",
    "power": "W",
    "heartrate": "BPM",
    "speed": "kph",
    "run_cadence": "strides/min",
    "ground_contact_time": "ms",
    "vertical_ratio": "%",
    "vertical_oscillation": "mm",
    "stride_length": "mm",
    "tire_pressure_mbar": "mbar",
    "sensor_location": "",
    "core_temperature_c": "°C",
    "skin_temperature_c": "°C"
};

fa_datatype_class = {
    "power": '<i class="fas fa-bolt"></i>',
    "heartrate": '<i class="fas fa-heartbeat"></i>',
    "cadence": '<i class="fas fa-sync-alt"></i>',
    "speed": '<i class="fas fa-tachometer-alt"></i>',
    "SMO2": '<i class="fas fa-wind"></i>',
    "Saturation": '<i class="fas fa-percentage"></i>',
    "Previous Saturation": '<i class="fas fa-percentage"></i>',
    "run_cadence": '<i class="fas fa-running"></i>',
    "ground_contact_time": '<i class="fas fa-stopwatch-20"></i>',
    "vertical_ratio": '<i class="fas fa-percent"></i>',
    "vertical_oscillation": '<i class="fas fa-arrows-alt-v"></i>',
    "stride_length": '<i class="fas fa-arrows-alt-h"></i>',
    "tire_pressure_mbar": '<img src="./imgs/tpms.png"></i>',
    "sensor_location": '<i class="fas fa-arrows-alt-h"></i>',
    "core_temperature_c": '<i class="fas fa-temperature-high"></i>',
    "skin_temperature_c": '<i class="fas fa-temperature-high"></i>'
}

/**
 * Generate ID of plot
 * @param device_id: ID of the ANT sensor
 * @param data_type: Type of the data displayed in the plot
 */
 function plotId(device_id, data_type) {
    return "plot_" + device_id + "_" + data_type;
}